name: Docker Build and Push

# 触发条件：当 main 分支有 push 或 pull_request 时触发
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    
    steps:
      # 1. 拉取代码
      - name: 拉取代码
        uses: actions/checkout@v4

      # 2. 设置 QEMU (用于支持多平台编译，可选)
      - name: 设置 QEMU
        uses: docker/setup-qemu-action@v3

      # 3. 设置 Docker Buildx
      - name: 设置 Docker Buildx
        uses: docker/setup-buildx-action@v3

      # 4. 登录到 Docker Hub
      - name: 登录到 Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      # 5. 编译并推送镜像
      
      - name: 编译并推送镜像
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile
          push: true
          # 替换 lumia1998 为你的 Docker Hub 用户名
          # 替换 image-forward 为你的镜像名称
          tags: |
            lumia1998/image-forward:latest
            lumia1998/image-forward:${{ github.sha }}